# Dataset configuration
dataset:
  data_files:
    training: 'data/triangular/train_100000.h5'
    validation: 'data/triangular/val_10000.h5'
  # Number of measures per configuration
  nmeasures: 1000
  batch_size: 64
  labels_choice: [0, 1]
  basis_type: 'computational'
# Model configuration
model:
  model_dir: 'results/conv_model'
  predefined_model: null
  model_type: 'conv' # plain/conv/recurrent
  layers:
    frequency_layer: 1 # False/None or spin of the qudits
    conv_layers: [
      {filters: 128, kernel_size: [1, 2], strides: [1, 1], activation: 'relu'},
      # {filters: 32, kernel_size: [1, 2], strides: [1, 1], activation: 'relu'},
      # {filters: 8, kernel_size: [1, 2], strides: [1, 1], activation: 'relu'},
      {filters: 2, kernel_size: [1, 2], strides: [1, 1], activation: 'relu'}
      {filters: 2, kernel_size: [3, 1], strides: [1, 1], activation: 'relu'}
    ]
    dense_layers: [
      # {units: 32, activation: 'relu'}
    ]
  dropout: 0
# Training configuration
training:
  loss: 'mse'
  metrics: 'mae'
  adam_config: {learning_rate: 0.001}
  epochs: 25
# Plots configuration
plotting:
  plot_model: true
  log_scale: true