# Dataset configuration
dataset:
  data_files:
    training: 'data/triangular/train_100000.h5'
    validation: 'data/triangular/val_10000.h5'
  # Number of measures per configuration
  nmeasures: 1000
  batch_size: 256
  labels_choice: [0, 1]
  basis_type: 'algebraic'
# Model configuration
model:
  model_dir: 'results/plain_model'
  predefined_model: null
  model_type: 'plain' # plain/conv/recurrent
  layers:
    dense_layers: [
      {units: 256, activation: 'tanh'},
      {units: 256, activation: 'tanh'},
    ]
  dropout: 0.001
# Training configuration
training:
  loss: 'mse'
  metrics: 'mae'
  adam_config: {learning_rate: 0.001}
  epochs: 50
# Plots configuration
plotting:
  plot_model: true
  log_scale: true