# Dataset configuration
dataset:
  data_files:
    training: 'data/triangular/train_100000.h5'
    validation: 'data/triangular/val_10000.h5'
  # Number of measures per configuration
  nmeasures: 10000
  batch_size: 64
  labels_choice: [0, 1]
  basis_type: 'computational' # computational/algebraic
# Model configuration
model:
  model_dir: 'results/plain_model'
  predefined_model: null
  model_type: 'plain' # plain/conv/recurrent
  layers:
    dense_layers: [
      {units: 500, activation: 'relu', kernel_initializer: 'he_normal'},
      {units: 500, activation: 'relu', kernel_initializer: 'he_normal'},
    ]
  dropout: 0
# Training configuration
training:
  loss: 'mae'
  metrics: 'mae'
  adam_config: {learning_rate: 0.01}
  epochs: 100
# Plots configuration
plotting:
  plot_model: true
  log_scale: true