# Dataset configuration
dataset:
  data_files:
    training: 'data/triangular/train_100000.h5'
    validation: 'data/triangular/val_10000.h5'
  # Number of measures per configuration
  nmeasures: 10000
  batch_size: 64
  labels_choice: [0, 1]
  basis_type: 'computational' # computational/algebraic
# Model configuration
model:
  model_dir: 'results/recurrent_model'
  predefined_model: null
  model_type: 'recurrent' # plain/conv/recurrent
  recurrent_type: 'RNN' # RNN/LSTM/GRU
  layers:
    spin_average: false
    recurrent_layers: [
# Plots configuration
      {units: 100, activation: 'relu', kernel_initializer: 'he_normal', return_sequences: True},
      {units: 100, activation: 'relu', kernel_initializer: 'he_normal', return_sequences: False},
    ]
    dense_layers: []
  dropout: 0
# Training configuration
training:
  loss: 'mae' # mse/mae/msle/logcosh/huber
  metrics: 'mae'
  adam_config: {learning_rate: 0.001}
  epochs: 100
# Plots configuration
plotting:
  plot_model: true
  log_scale: true