# Dataset configuration
dataset:
  data_files:
    training: 'data/D_theta_fixed/dataset_5_10000.h5'
    validation: 'data/D_theta_fixed/dataset_5_10000.h5'
    test: null
  # Number of measures per configuration
  nmeasures: 1000
  batch_size: 64
  labels_choice: [2]
  basis_type: 'computational'
# Model configuration
model:
  model_dir: 'results/recurrent_model'
  predefined_model: null
  model_type: 'recurrent' # plain/conv/recurrent
  recurrent_type: 'LSTM'
  layers:
    recurrent_layers: [
      {units: 100, dropout: 0.05, recurrent_dropout: 0.2, return_sequences: True},
      {units: 10, dropout: 0.05, recurrent_dropout: 0.2, return_sequences: True},
      {units: 1, dropout: 0.05, recurrent_dropout: 0.2, return_sequences: False},
    ]
    dense_layers: []
  dropout: 0
# Training configuration
training:
  loss: 'mse'
  metrics: 'mae'
  adam_config: {learning_rate: 0.001}
  epochs: 10
# Plots configuration
plotting:
  plot_model: true
  log_scale: true